In [1]:
source("mediation_simulation.r")

In [2]:
output=simulate_simple_mediation(3,8,4,1)
output

$OTU
                [,1]       [,2]         [,3]
          0.02485521  0.6990284  0.408175763
          0.76293577  0.3168589  0.586317356
          0.45977920  0.8872053  0.668616426
          0.43614826  0.7071642  0.001383757
          0.42392056  0.3634555  0.274824285
          0.60230049  0.7930852  0.866551771
producer  0.89943546  0.4467124  0.807260028
target   -3.09339090 -1.5690626 -4.807483626

$Metabolite
           [,1]      [,2]      [,3]
[1,] 0.96046491 0.7291583 0.9524750
[2,] 0.19394808 0.4733477 0.8484302
[3,] 0.01210569 0.2296636 0.4896710
[4,] 2.60561277 1.9619104 3.2698385

$OtuAnn
  Species
1    OTU1
2    OTU2
3    OTU3
4    OTU4
5    OTU5
6    OTU6
7    OTU7
8    OTU8

$MetAnn
      Species
1          M1
2          M2
3 M3 Mediator
4 M4 Mediator

In [25]:
qx=qr(output$OTU[1:6,1:4])

In [27]:
solve.qr(qx,output$OTU[7,1:4])

ERROR: Error in qr.coef(a, b): 'qr' and 'y' must have the same number of rows


In [4]:
n=2
p_otu=4
p_metabolite=2
mediations=1

not_mediation_otu = p_otu-2*mediations
not_mediation_metabolite = p_metabolite-mediations

In [15]:
not_mediation_otu

[1] 2

In [16]:
not_mediation_metabolite

[1] 1

In [17]:
otutable

[,1]       [,2]     
[1,] 0.08999007 0.7820796
[2,] 0.77619082 0.2580139

In [18]:
metabolitetable

[,1]     [,2]     
[1,] 0.838959 0.3020534

In [5]:
not_mediation_otu <- p_otu - 2*mediations
not_mediation_metabolite <- p_metabolite - mediations
otutable <- t(replicate(not_mediation_otu, runif(n)))

In [6]:
otutable

[,1]       [,2]     
[1,] 0.08999007 0.7820796
[2,] 0.77619082 0.2580139

In [8]:
replicate(not_mediation_otu, runif(n))

[,1]       [,2]     
[1,] 0.60144531 0.1696044
[2,] 0.08321782 0.6476755

In [10]:
output$OTU

[,1]       [,2]       
          0.3234818  0.80590320
          0.1608200  0.05818254
producer  0.5860819  0.53949878
target   -1.8192517 -0.55375749

In [12]:
metabolitetable <- t(replicate(not_mediation_metabolite, runif(n)))

In [13]:
metabolitetable

[,1]     [,2]     
[1,] 0.838959 0.3020534

In [14]:
not_mediation_metabolite

[1] 1