In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
from mediation_simulation import *

In [7]:
from numpy.linalg import inv,qr,solve,lstsq
from scipy.linalg import eigh

In [8]:
from numpy.random import multivariate_normal

<hr><hr><hr>

In [43]:
from simulation import Simulation
var={'n':5,
     'p_otu':8, 
     'p_metabolite':4}

ModuleNotFoundError: No module named '__main__.simulation'; '__main__' is not a package

In [38]:
s = Simulation(**var)

In [39]:
s.run_simulation()

(array([[-1.09413052, -2.86358108, -1.62928476, -2.91730696, -2.34072162],
        [ 0.67110169,  0.5672773 ,  0.5480107 ,  0.66870114,  0.62176282],
        [ 0.11386258,  0.11963216,  0.46145456,  0.02473795,  0.08133202],
        [ 0.77462969,  0.31965929,  0.80809586,  0.42164611,  0.05315723],
        [ 0.61042962,  0.11218116,  0.82654212,  0.80768169,  0.61371448],
        [ 0.39765992,  0.74695329,  0.58868682,  0.59768379,  0.78682943],
        [ 0.51800812,  0.54575577,  0.55992744,  0.73430938,  0.28283605],
        [ 0.39925949,  0.98636964,  0.9639952 ,  0.53638257,  0.97614645]]),
 array([[0.85376172, 1.09777181, 1.07947054, 0.49560908, 0.00110802],
        [0.79027549, 0.88549468, 0.04341083, 0.68010514, 0.62150833],
        [0.8900151 , 0.74157567, 0.87349379, 0.62200742, 0.26275196],
        [0.14156715, 0.17102327, 0.95294667, 0.38739045, 0.89263562]]))

In [40]:
s.is_dependent

array([1., 0., 0., 0., 0., 0., 0., 0.])

<hr><hr><hr>

In [9]:
var={'n':5,
     'p_otu':8, 
     'p_metabolite':4, 
     'mediations':1,
     'mediation_func':multi_var_mediation
    }

truth_coef={
    'beta11':-2,
    'beta21':2,
    'beta32':-1.5
}

NameError: name 'multi_var_mediation' is not defined

In [68]:
output=simulate_simple_mediation(**var)

In [69]:
output["OTU"]

matrix([[  0.85954909,   0.74070169,   0.22128909,   0.42653442,
           0.30955746],
        [  0.69135427,   0.44331381,   0.52861219,   0.13873374,
           0.96870398],
        [  0.22807235,   0.5334323 ,   0.63143952,   0.40239475,
           0.70733449],
        [  0.82499205,   0.22460585,   0.05925081,   0.19797856,
           0.26667491],
        [  0.59895953,   0.85522022,   0.98378675,   0.93477717,
           0.29077958],
        [  0.36085925,   0.41000061,   0.25967223,   0.30522432,
           0.96787329],
        [  1.6451183 ,   1.3156046 ,   0.58719372,   0.81136577,
          -0.5321573 ],
        [ -6.86839355, -10.08565447,  -3.99298396,  -4.98718679,
           1.20197871]])

In [86]:
import pandas as pd
pd.DataFrame(multi_var_mediation(6)['OTU'])

0         1         2         3         4         5
0  0.616196  1.446333  0.822214  1.370013 -0.556714 -0.002943
1 -5.137859 -8.211168 -2.068757 -7.515939  1.787345 -0.259962

In [74]:
(np.random.multivariate_normal(3,_A(3))
             +np.random.rand(3))

NameError: name '_A' is not defined

<hr><hr>

In [20]:
n=5
m=np.zeros((n,n))
np.fill_diagonal(m,1)
for i,j in ((1,0),(3,2)):
    m[i,j]=1
    m[j,i]=1
m

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
E,_=eigh(m)
all(E>=0)

True

In [44]:
n=3
(np.random.multivariate_normal(np.zeros(A.shape[0]),A,size=n)
             +np.random.rand(5))

array([[ 1.21648903,  1.79526987,  0.13492755, -0.11878648, -0.88300113],
       [ 0.43722764,  1.01600847,  0.67914257,  0.42542856,  0.70962726],
       [-0.82705622, -0.24827539,  1.04972768,  0.79601366,  1.5952337 ]])

In [58]:
multi_var_mediation(m)

{'OTU': array([[ 0.91489916,  0.97445274, -0.43176479,  0.12025238, -0.93237344],
        [-2.74424465, -5.69584803,  3.83024112,  1.12514827,  3.10619331]]),
 'Metabolite': array([[ 1.89804088,  2.10985729, -1.53425391,  0.40175619, -2.05485462]])}

In [55]:
simple_mediation(5)["OTU"]

array([[ 0.38761842,  0.84565225,  0.92599178,  0.38934802,  0.93610891],
       [-0.37078305, -3.68580675, -5.11489282, -1.23303441, -5.49853996]])

In [56]:
multivariate_normal(np.zeros(5),A)

array([ 0.09710134,  0.09710134, -0.03743911, -0.0374391 ,  0.613341  ])

In [35]:
A=m
n=A.shape[0]
producer=(np.random.multivariate_normal(np.zeros(n),A,size=n)
         +np.random.rand(n))
producer

array([[-2.11504819, -2.82738011, -0.18941214,  0.13350821,  0.85738217],
       [ 0.3566925 , -0.35563944,  2.3634472 ,  2.68636755,  0.27014644],
       [ 1.65091378,  0.93858185, -0.07044582,  0.25247451,  0.799968  ],
       [-1.47157362, -2.18390555,  0.76470267,  1.08762303,  1.40879452],
       [ 0.31349103, -0.3988409 , -0.454042  , -0.13112166,  0.36434141]])

In [37]:
producer

array([[-2.11504819, -2.82738011, -0.18941214,  0.13350821,  0.85738217],
       [ 0.3566925 , -0.35563944,  2.3634472 ,  2.68636755,  0.27014644],
       [ 1.65091378,  0.93858185, -0.07044582,  0.25247451,  0.799968  ],
       [-1.47157362, -2.18390555,  0.76470267,  1.08762303,  1.40879452],
       [ 0.31349103, -0.3988409 , -0.454042  , -0.13112166,  0.36434141]])

<hr><hr><hr>

In [11]:
a=np.random.rand(20).reshape((4,5))

In [34]:
np.random.rand(10,10).shape

(10, 10)

In [40]:
multi_var_mediation(5)

{'OTU': array([[  2.40447881,   2.12028552,   1.78767821,   2.07711469,
           0.9724978 ],
        [  1.01692674,   1.48927675,   1.77197809,   0.79490353,
           2.34675115],
        [  1.06630122,   0.0437236 ,  -0.31505709,   0.7795981 ,
           0.30889588],
        [  1.24509397,   0.02219495,   1.65645071,   1.15282809,
           0.98934482],
        [  2.43580765,   1.35396732,   2.40601926,   2.62250526,
           2.88045493],
        [-12.05646206, -10.08124712,  -9.37077836,  -7.71726287,
          -5.63467205],
        [ -5.11870174,  -6.92620327,  -9.29227776,  -1.30620705,
         -12.5059388 ],
        [ -5.36557411,   0.30156245,   1.14289812,  -1.2296799 ,
          -2.31666244],
        [ -6.25953788,   0.40920574,  -8.71464084,  -3.09582986,
          -5.71890713],
        [-12.21310627,  -6.24965615, -12.4624836 , -10.44421569,
         -15.17445767]]),
 'Metabolite': array([[[ 4.37130653e+00,  4.17908748e+00,  4.19981809e+00,
           3.74167521e+00,

In [15]:
a.T.dot(a)

array([[1.3436178 , 0.92492296, 0.62625861, 1.40983374, 1.21372262],
       [0.92492296, 1.38837076, 1.12801212, 0.93485303, 1.19755506],
       [0.62625861, 1.12801212, 1.44448002, 0.71979802, 1.30921151],
       [1.40983374, 0.93485303, 0.71979802, 1.66032557, 1.60971923],
       [1.21372262, 1.19755506, 1.30921151, 1.60971923, 2.07256559]])

In [27]:
a=np.matrix([
    [0,0,1,1],
    [0,0,0,0],
    [1,0,0,0],
    [1,0,0,0]
])
e,_=eigh(a.T.dot(a))
all(e>=0)

True

In [28]:
c=a.T.dot(a)
m=np.zeros(4)

In [29]:
c

matrix([[2, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 1]])

In [35]:
multivariate_normal(m,c)

array([-0.71914357,  0.        ,  1.11094496,  1.11094496])

In [20]:
E,V=eigh(a.T.dot(a))
all(E>=0)

True

In [22]:
c=a.T.dot(a)
m=np.zeros(5)

In [23]:
multivariate_normal(m,c)

array([ 0.82683249,  0.87217464, -0.37500823,  1.07730663,  0.7755822 ])

In [273]:
var={'n':4, 'p_otu':8, 'p_metabolite':4, 'mediations':1}

<hr>

In [310]:
from linReg import *

In [278]:
output=simulate_simple_mediation(**var)

In [280]:
X,y=output["OTU"][:-1,:],output["OTU"][-1,:]

In [342]:
output["OTU"]

matrix([[ 0.25942256,  0.37381314,  0.58759964,  0.2728219 ],
        [ 0.3708528 ,  0.19705428,  0.45985588,  0.0446123 ],
        [ 0.79979588,  0.07695645,  0.51883515,  0.3068101 ],
        [ 0.57754295,  0.95943334,  0.64557024,  0.03536244],
        [ 0.43040244,  0.51001685,  0.53617749,  0.68139251],
        [ 0.2775961 ,  0.12886057,  0.39267568,  0.95640572],
        [ 0.75677864,  0.63606106,  0.24002027,  0.16053882],
        [-5.62848601,  0.26479425, -0.9155853 , -1.81689762]])

# 1. $$Y=\beta_{32}\cdot\beta_{21}X+\epsilon$$
$X\in\mathbb{R}^{(\text{p_otu}-1)\times n}$

$Y\in\mathbb{R}^{1\times n}$

$\Rightarrow\enspace(\beta_{32}\cdot\beta_{21})\in\mathbb{R}^{\text{p_otu}-1)\times 1}$

In [356]:
X.shape,y.shape

((7, 4), (1, 4))

In [357]:
coef, vcov, sigma,df=linmodEst(X,y)

In [358]:
display(sigma,coef)

1.0864928258298578e-14

matrix([[ 2.60476843, -0.22636003, -5.56602033,  2.30603029,  0.60033872,
         -0.65493813, -4.19806485]])

## step 1: $$Y=\beta_{10}+\beta_{11}X+\epsilon_{1}$$

In [359]:
# add dummy variable for beta10
X_1=np.vstack([X,np.ones(X.shape[1])])
X_1.shape

(8, 4)

In [360]:
coef, vcov, sigma,df=linmodEst(X_1,y)

In [361]:
display(sigma,coef)

6.26391136359801e-15

matrix([[ 2.69072387, -0.21170264, -5.52212721,  2.4480739 ,  0.80087149,
         -0.45825167, -4.06127033, -0.3893087 ]])

In [385]:
beta11,beta10=coef[:,:-1],coef[:,-1]

In [387]:
beta11.dot(X)+beta10

matrix([[-5.62848601,  0.26479425, -0.9155853 , -1.81689762]])

## step 2: $$Me=\beta_{20}+\beta_{21}X+\epsilon_{2}$$

In [399]:
coef2, vcov2, sigma2,df2=linmodEst(X_1,output["Metabolite"])

In [400]:
display(sigma2)

3.8520299406335125e-15

In [401]:
beta21,beta20=coef2[:,:-1],coef2[:,-1]

In [402]:
beta21.dot(X)+beta20

matrix([[0.18713089, 0.90398395, 0.54380595, 0.45691142],
        [0.88204141, 0.45860396, 0.72416764, 0.39902532],
        [0.90404439, 0.69002502, 0.69962205, 0.3277204 ],
        [3.81747398, 0.21210629, 0.34409085, 1.45796901]])

## step 3: $$Y=\beta_{30}+\beta_{31}X+\beta_{32}Me+\epsilon_{3}$$

In [404]:
XMe1=np.vstack([X,output["Metabolite"],np.ones(X.shape[1])])

In [407]:
coef3, vcov3, sigma3,df3=linmodEst(XMe1,y)

In [447]:
display(sigma3,coef3)

1.6059904674447437e-15

matrix([[-0.2088658 , -0.45007648, -0.75204656,  0.20705928,  0.14666732,
          0.03515756,  0.24913621,  0.65152058, -0.49914841, -0.21739158,
         -1.25228999,  0.10854822]])

In [455]:
beta30,beta31,beta32=coef3[:,-1],coef3[:,:X.shape[0]],coef3[:,X.shape[0]:-1]

In [456]:
display(beta30,beta31,beta32)

matrix([[0.10854822]])

matrix([[-0.2088658 , -0.45007648, -0.75204656,  0.20705928,  0.14666732,
          0.03515756,  0.24913621]])

matrix([[ 0.65152058, -0.49914841, -0.21739158, -1.25228999]])

In [458]:
beta30+beta31.dot(X)+beta32.dot(output["Metabolite"])

matrix([[-5.62848601,  0.26479425, -0.9155853 , -1.81689762]])

<hr>

In [460]:
np.abs(beta31)<np.abs(beta11)

matrix([[ True, False,  True,  True,  True,  True,  True]])

<hr>

In [337]:
X.shape,np.ones(X.shape[1]).reshape(-1,1)

((7, 4), array([[1.],
        [1.],
        [1.],
        [1.]]))

In [338]:
X_1=np.hstack([X,np.ones(X.shape[0]).reshape(-1,1)])

In [340]:
q_1,r_1=qr(X_1)

In [341]:
coef, vcov, sigma,df=linmodEst(X_1,y)

ValueError: shapes (7,5) and (4,1) not aligned: 5 (dim 1) != 4 (dim 0)

In [321]:
coef

matrix([[ 2.60476843, -0.22636003, -5.56602033,  2.30603029,  0.60033872,
         -0.65493813, -4.19806485]])

In [322]:
sigma

1.0864928258298578e-14

In [323]:
vcov

matrix([[ 2.71162588e-28, -8.02710526e-29, -1.82177112e-28,
         -8.00712217e-30],
        [-8.02710526e-29,  2.44987828e-28, -1.66067200e-28,
          5.77595156e-29],
        [-1.82177112e-28, -1.66067200e-28,  4.70268126e-28,
         -1.43238769e-28],
        [-8.00712217e-30,  5.77595156e-29, -1.43238769e-28,
          1.56749127e-28]])

In [324]:
df

3

In [328]:
lstsq(X.T,y.T)

/Users/indigo410/anaconda3/envs/DSC/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(matrix([[ 2.60476843],
         [-0.22636003],
         [-5.56602033],
         [ 2.30603029],
         [ 0.60033872],
         [-0.65493813],
         [-4.19806485]]),
 matrix([], shape=(1, 0), dtype=float64),
 4,
 array([2.37212817, 0.9858072 , 0.58130101, 0.42570712]))

<hr>
Apr 14

In [272]:
output=simulate_simple_mediation(**var)

In [274]:
display(output)

{'OTU': matrix([[ 0.49739137,  0.63947252,  0.36858461,  0.13690027],
         [ 0.82211773,  0.18984791,  0.51131898,  0.22431703],
         [ 0.09784448,  0.86219152,  0.97291949,  0.96083466],
         [ 0.9065555 ,  0.77404733,  0.33314515,  0.08110139],
         [ 0.40724117,  0.23223414,  0.13248763,  0.05342718],
         [ 0.72559436,  0.01142746,  0.77058075,  0.14694665],
         [ 0.26211815,  0.45614057,  0.68328134,  0.69562545],
         [ 0.5756451 ,  0.51188637, -2.13990257, -0.52844524]]),
 'Metabolite': matrix([[ 0.07952208,  0.08960303,  0.67204781,  0.24536721],
         [ 0.42053947,  0.55736879,  0.86055117,  0.72704426],
         [ 0.27032791,  0.1314828 ,  0.05537432,  0.30159863],
         [-0.28912796, -0.55414319,  1.88762755,  0.81546292]]),
 'OtuAnn': {'Species': ['OTU1',
   'OTU2',
   'OTU3',
   'OTU4',
   'OTU5',
   'OTU6',
   'OTU7',
   'OTU8']},
 'MetAnn': {'Species': ['M1', 'M2', 'M3 Mediator', 'M4 Mediator']}}

In [276]:
output['OTU'].shape

(8, 4)

In [277]:
output['OTU']

matrix([[ 0.49739137,  0.63947252,  0.36858461,  0.13690027],
        [ 0.82211773,  0.18984791,  0.51131898,  0.22431703],
        [ 0.09784448,  0.86219152,  0.97291949,  0.96083466],
        [ 0.9065555 ,  0.77404733,  0.33314515,  0.08110139],
        [ 0.40724117,  0.23223414,  0.13248763,  0.05342718],
        [ 0.72559436,  0.01142746,  0.77058075,  0.14694665],
        [ 0.26211815,  0.45614057,  0.68328134,  0.69562545],
        [ 0.5756451 ,  0.51188637, -2.13990257, -0.52844524]])

<hr>

In [248]:
X.shape

(7, 5)

In [249]:
q,r=np.linalg.qr(X)

In [255]:
q.shape,y.shape

((7, 5), (1, 5))

In [270]:
inv(X.T.dot(X)).dot(X.T)

(5, 7)

In [271]:
output["OTU"].shape,output["Metabolite"].shape

((8, 4), (4, 4))

UPDATE: 
- chagned all array to matrix for easier computation
- //changed dimension of `Metabolite`: tranposed.

In [197]:
var={'n':4, 'p_otu':8, 'p_metabolite':4, 'mediations':1}

In [205]:
# np.random.seed(0)
output=simulate_simple_mediation(**var)
output

{'OTU': matrix([[ 0.27762871,  0.58678435,  0.86385561,  0.11753186],
         [ 0.51737911,  0.13206811,  0.71685968,  0.3960597 ],
         [ 0.56542131,  0.18327984,  0.14484776,  0.48805628],
         [ 0.35561274,  0.94043195,  0.76532525,  0.74866362],
         [ 0.90371974,  0.08342244,  0.55219247,  0.58447607],
         [ 0.96193638,  0.29214753,  0.24082878,  0.10029394],
         [ 0.23170163,  0.94931882,  0.9413777 ,  0.79920259],
         [-3.0048195 , -3.73383348, -4.02064547, -1.31882738]]),
 'Metabolite': matrix([[0.01642963, 0.92952932, 0.66991655, 0.78515291],
         [0.28173011, 0.58641017, 0.06395527, 0.4856276 ],
         [0.97749514, 0.87650525, 0.33815895, 0.96157015],
         [1.37358216, 2.21585586, 2.66908337, 1.13198608]]),
 'OtuAnn': {'Species': ['OTU1',
   'OTU2',
   'OTU3',
   'OTU4',
   'OTU5',
   'OTU6',
   'OTU7',
   'OTU8']},
 'MetAnn': {'Species': ['M1', 'M2', 'M3 Mediator', 'M4 Mediator']}}

In [202]:
simple_mediation_direct(4)["OTU"]

array([[ 0.61801543,  0.4287687 ,  0.13547406,  0.29828233],
       [-5.59968501, -1.59701334, -3.475764  , -1.45145757]])

<hr>

In [206]:
output["OTU"]

matrix([[ 0.27762871,  0.58678435,  0.86385561,  0.11753186],
        [ 0.51737911,  0.13206811,  0.71685968,  0.3960597 ],
        [ 0.56542131,  0.18327984,  0.14484776,  0.48805628],
        [ 0.35561274,  0.94043195,  0.76532525,  0.74866362],
        [ 0.90371974,  0.08342244,  0.55219247,  0.58447607],
        [ 0.96193638,  0.29214753,  0.24082878,  0.10029394],
        [ 0.23170163,  0.94931882,  0.9413777 ,  0.79920259],
        [-3.0048195 , -3.73383348, -4.02064547, -1.31882738]])

In [192]:
output["OTU"].shape

(8, 4)

In [207]:
output['OtuAnn']['Species']

['OTU1', 'OTU2', 'OTU3', 'OTU4', 'OTU5', 'OTU6', 'OTU7', 'OTU8']

In [211]:
i,j=0,1

In [215]:
tij=np.var(np.log(output["OTU"][i]/output["OTU"][j]))

In [216]:
tij

1.0289741042028886

In [217]:
rou=np.zeros(output["OTU"].shape[0])

In [218]:
from itertools import combinations

In [233]:
c=combinations(np.arange(output["OTU"].shape[0]-1),2)
t=np.matrix(np.zeros((output["OTU"].shape[0]-1,output["OTU"].shape[0]-1)))
for i,j in c:
    t[i,j]=np.var(np.log(output["OTU"][i])-np.log(output["OTU"][j]))
    
display(t)

matrix([[0.        , 1.0289741 , 1.72749655, 0.55662716, 1.98354854,
         0.87223993, 0.65499813],
        [0.        , 0.        , 0.61980856, 0.77310866, 0.18221263,
         0.95387017, 0.98853462],
        [0.        , 0.        , 0.        , 0.79495121, 0.57563544,
         0.81512945, 1.20443316],
        [0.        , 0.        , 0.        , 0.        , 1.46027722,
         1.23628376, 0.05634204],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         1.24067122, 1.80748554],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 1.75784199],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]])

In [234]:
np.round(t,3)

array([[0.   , 1.029, 1.727, 0.557, 1.984, 0.872, 0.655],
       [0.   , 0.   , 0.62 , 0.773, 0.182, 0.954, 0.989],
       [0.   , 0.   , 0.   , 0.795, 0.576, 0.815, 1.204],
       [0.   , 0.   , 0.   , 0.   , 1.46 , 1.236, 0.056],
       [0.   , 0.   , 0.   , 0.   , 0.   , 1.241, 1.807],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 1.758],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [235]:
output["OTU"]

matrix([[ 0.27762871,  0.58678435,  0.86385561,  0.11753186],
        [ 0.51737911,  0.13206811,  0.71685968,  0.3960597 ],
        [ 0.56542131,  0.18327984,  0.14484776,  0.48805628],
        [ 0.35561274,  0.94043195,  0.76532525,  0.74866362],
        [ 0.90371974,  0.08342244,  0.55219247,  0.58447607],
        [ 0.96193638,  0.29214753,  0.24082878,  0.10029394],
        [ 0.23170163,  0.94931882,  0.9413777 ,  0.79920259],
        [-3.0048195 , -3.73383348, -4.02064547, -1.31882738]])

In [239]:
q,r=qr(output["OTU"][:-1,:])

In [244]:
inv(r).dot(q.T).dot()

matrix([[ 0.04766462, -0.10283458,  0.22031977, -0.05010988,  0.18896534,
          0.86248785, -0.29008228],
        [ 0.17366998, -0.91897015,  0.06051231,  0.63216853, -0.75402089,
          0.82332381,  0.24883937],
        [ 0.8056638 ,  0.90091707, -0.56436891, -0.40578897,  0.28051735,
         -0.50317251,  0.01782351],
        [-1.00888002,  0.12841614,  0.62917102,  0.29835693,  0.51422355,
         -0.83778529,  0.40133587]])

In [241]:
# p = np.dot(q.T, b)
# np.dot(LA.inv(r), p)

In [116]:
b=inv(X.T.dot(X)).dot(X.T).dot(y)
b

matrix([[0.53383989]])

In [118]:
yhat=X.dot(b)
display(yhat,Y)

matrix([[ 0.29297854],
        [ 0.32177913],
        [ 0.22616383],
        [-1.49438647]])

matrix([[1.27435369],
        [1.24562081]])

-> QR decomposition

In [82]:
Q,R=qr(X)
display(Q,R)

matrix([[-0.63543597, -0.7675895 ],
        [-0.03644378, -0.07863182],
        [-0.77129306,  0.63610014]])

matrix([[-0.9193773 , -0.59439329],
        [ 0.        , -0.20851847]])

In [83]:
b=inv(R).dot(Q.T).T.dot(y)
display(b)

matrix([[-6.03818892],
        [-0.5437124 ],
        [ 1.61356102]])

In [86]:
yhat=X.T.dot(b)
display(yhat,y)

matrix([[-2.40156885],
        [-2.74204299]])

matrix([[-2.40156885],
        [-2.74204299]])

In [105]:
np.random.seed(0)
simple_mediation(2)['OTU']

array([[ 0.5488135 ,  0.71518937],
       [-2.34461651, -7.91456451]])

In [104]:
output["OTU"]

matrix([[ 0.5488135 ,  0.71518937],
        [ 0.60276338,  0.54488318],
        [ 0.4236548 ,  0.64589411],
        [-2.79931588, -1.30004802]])

<hr>

In [113]:
output=simulate_simple_mediation(2,4,2)

In [103]:
temp=simple_mediation_direct(2)

In [104]:
temp

{'OTU': array([[ 0.53600357,  0.03278812],
        [-1.75817784, -0.01439248]]),
 'Metabolite': array([[ 1.9770727 , -0.09877941]])}

In [105]:
otutable

array([[0.96556086, 0.63188856],
       [0.18718298, 0.75499973]])

In [106]:
temp["OTU"]

array([[ 0.53600357,  0.03278812],
       [-1.75817784, -0.01439248]])

In [110]:
np.stack([otutable,temp["OTU"]],axis=0)

array([[[ 0.96556086,  0.63188856],
        [ 0.18718298,  0.75499973]],

       [[ 0.53600357,  0.03278812],
        [-1.75817784, -0.01439248]]])

In [114]:
for key in output.keys():
    display(key,output[key])

'OTU'

array([[ 0.78645644,  0.49210526],
       [ 0.60425343,  0.60293061],
       [ 0.85324443,  0.89717775],
       [-2.69355103, -0.69199418]])

'Metabolite'

array([[0.11033147, 0.76258593],
       [1.73951789, 1.64841864]])

'OtuAnn'

{'Species': ['OTU1', 'OTU2', 'OTU3', 'OTU4']}

'MetAnn'

{'Species': ['M1 Mediator', 'M2 Mediator']}